#' Bethel Test Fishery CPUE Records
#'
#' Data set containing the daily catch-per-unit-effort index generated by the Bethel Test Fishery,
#'   operated by the Alaska Department of Fish and Game.
#'
#' @format See `vignette("datasets", package = "KuskoHarvData")`.
#' @note This data set needs to be updated manually,
#'     see Step 5 in `vignette("updating-data", package = "KuskoHarvData")`.
#' @source This CPUE index is used as an index of in-river abundance, species composition, and -- at the end of the season -- run timing.
#'     It can be found on the [ADF&G Bethel Test Fishery website](https://www.adfg.alaska.gov/index.cfm?adfg=commercialbyareakuskokwim.btf).
#'     Sampling methods are described in Bue and Lipka ([2016](http://www.adfg.alaska.gov/FedAidPDFs/FDS16-05.pdf)).
#'

"btf_master"
