#' Bethel Test Fishery CPUE Data
#'
#' A data set containing the daily catch-per-unit-effort index generated by the Bethel Test Fishery,
#'   operated by the Alaska Department of Fish and Game
#'
#' @format A data frame with rows representing a unique day- and species-specific record.
#'   Variables include:
#'   * `date`: the date sampling occurred; only dates between June 1 and August 24 in years after and including 2016 are included
#'   * `species`: the species for which `cpue` and `ccpue` apply; only Chinook, chum, and sockeye salmon are included
#'   * `cpue`: the daily value of catch-per-unit-effort
#'   * `ccpue`: the cumulative value of catch-per-unit effort
#' @note This data set will need to be updated regularly (at least annually).
#'   It can be found on the [ADF&G Bethel Test Fishery website](https://www.adfg.alaska.gov/index.cfm?adfg=commercialbyareakuskokwim.btf).
#'

"btf_master"
