#' Kuskokwim River Sonar Count Records
#'
#' Data set containing the daily counts generated by the Kuskokwim River sonar,
#'   operated by the Alaska Department of Fish and Game.
#'
#' @format See `vignette("datasets", package = "KuskoHarvData")`.
#' @note This data set needs to be updated manually,
#'     see Step 5 in `vignette("updating-data", package = "KuskoHarvData")`.
#' @source This data set is used as an index of in-river abundance, species composition, and -- at the end of the season -- run timing.
#'     It can be found on the [ADF&G Kuskokwim Escapement Fish Counts website](https://www.adfg.alaska.gov/index.cfm?adfg=commercialbyareakuskokwim.emihd).
#'     Sampling methods are described in Birchfield and Fletcher ([2025](https://www.adfg.alaska.gov/FedAidPDFs/FDS25-31.pdf)).
#'

"sonar_data_all"
